version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  studio:
    image: node:18.17.1
    working_dir: /app
    volumes:
      - .:/app
    command: npx prisma studio --port 5555
    ports:
      - "5555:5555"
    depends_on:
      - db

volumes:
  pgdata:
