# fly.toml app configuration file generated for katayaburi-api on 2023-09-21T02:42:18+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "katayaburi-api"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
